### ISSUE TITLE
How do I add this to Unity Package Manager via Git URL?

### ISSUE THREAD

**Issue by zipzit** [StansAssets/com.stansassets.scene-management#19]
ref: Unity 2019.4.18f1

If I go to "Package Manager" within the Unity Development Environment, there is an option (+ ▼) in corner for "Add Package from GIT URL.."   I've tried every link from this repo that remotely makes sense, but all I get is "Error adding package..."  

Note, there is also a choice with the Unity Package Manager to " Add package from tarball..."  but its clearly looking for a *.tgz file and not a tar.gz file...  which is what the release repo here provides.  So that's a fail, too..

Possible for you to address this at the intro README?  Many thanks for sharing your work, open source.

**Comment by stan-osipov** [comment]
Hey, sorry but you can not use it via the GIT URL. In order to do so, the package has to be in the repository root, which is not true for this one.

But you still have 2 options on how to install it. You can do it by adding our scope registry or by using OpenUPM, both are described here:
https://github.com/StansAssets/com.stansassets.scene-management/blob/master/README.md

Do you have any difficulties with it? Let me know, would be happy to help!
